// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Degree is the predicate function for degree builders.
type Degree func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Doctor is the predicate function for doctor builders.
type Doctor func(*sql.Selector)

// Nametitle is the predicate function for nametitle builders.
type Nametitle func(*sql.Selector)
