// Code generated by entc, DO NOT EDIT.

package department

const (
	// Label holds the string label denoting the department type in the database.
	Label = "department"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDepartment holds the string denoting the department field in the database.
	FieldDepartment = "department"

	// EdgeDoctor holds the string denoting the doctor edge name in mutations.
	EdgeDoctor = "doctor"

	// Table holds the table name of the department in the database.
	Table = "departments"
	// DoctorTable is the table the holds the doctor relation/edge.
	DoctorTable = "doctors"
	// DoctorInverseTable is the table name for the Doctor entity.
	// It exists in this package in order to avoid circular dependency with the "doctor" package.
	DoctorInverseTable = "doctors"
	// DoctorColumn is the table column denoting the doctor relation/edge.
	DoctorColumn = "department_id"
)

// Columns holds all SQL columns for department fields.
var Columns = []string{
	FieldID,
	FieldDepartment,
}

var (
	// DepartmentValidator is a validator for the "Department" field. It is called by the builders before save.
	DepartmentValidator func(string) error
)
