// Code generated by entc, DO NOT EDIT.

package nametitle

const (
	// Label holds the string label denoting the nametitle type in the database.
	Label = "nametitle"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNameTitle holds the string denoting the nametitle field in the database.
	FieldNameTitle = "name_title"

	// EdgeDoctor holds the string denoting the doctor edge name in mutations.
	EdgeDoctor = "doctor"

	// Table holds the table name of the nametitle in the database.
	Table = "nametitles"
	// DoctorTable is the table the holds the doctor relation/edge.
	DoctorTable = "doctors"
	// DoctorInverseTable is the table name for the Doctor entity.
	// It exists in this package in order to avoid circular dependency with the "doctor" package.
	DoctorInverseTable = "doctors"
	// DoctorColumn is the table column denoting the doctor relation/edge.
	DoctorColumn = "doctor_id"
)

// Columns holds all SQL columns for nametitle fields.
var Columns = []string{
	FieldID,
	FieldNameTitle,
}

var (
	// NameTitleValidator is a validator for the "NameTitle" field. It is called by the builders before save.
	NameTitleValidator func(string) error
)
