// Code generated by entc, DO NOT EDIT.

package nametitle

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/pmn-kao/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// NameTitle applies equality check predicate on the "NameTitle" field. It's identical to NameTitleEQ.
func NameTitle(v string) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNameTitle), v))
	})
}

// NameTitleEQ applies the EQ predicate on the "NameTitle" field.
func NameTitleEQ(v string) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNameTitle), v))
	})
}

// NameTitleNEQ applies the NEQ predicate on the "NameTitle" field.
func NameTitleNEQ(v string) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldNameTitle), v))
	})
}

// NameTitleIn applies the In predicate on the "NameTitle" field.
func NameTitleIn(vs ...string) predicate.Nametitle {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Nametitle(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldNameTitle), v...))
	})
}

// NameTitleNotIn applies the NotIn predicate on the "NameTitle" field.
func NameTitleNotIn(vs ...string) predicate.Nametitle {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Nametitle(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldNameTitle), v...))
	})
}

// NameTitleGT applies the GT predicate on the "NameTitle" field.
func NameTitleGT(v string) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldNameTitle), v))
	})
}

// NameTitleGTE applies the GTE predicate on the "NameTitle" field.
func NameTitleGTE(v string) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldNameTitle), v))
	})
}

// NameTitleLT applies the LT predicate on the "NameTitle" field.
func NameTitleLT(v string) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldNameTitle), v))
	})
}

// NameTitleLTE applies the LTE predicate on the "NameTitle" field.
func NameTitleLTE(v string) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldNameTitle), v))
	})
}

// NameTitleContains applies the Contains predicate on the "NameTitle" field.
func NameTitleContains(v string) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldNameTitle), v))
	})
}

// NameTitleHasPrefix applies the HasPrefix predicate on the "NameTitle" field.
func NameTitleHasPrefix(v string) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldNameTitle), v))
	})
}

// NameTitleHasSuffix applies the HasSuffix predicate on the "NameTitle" field.
func NameTitleHasSuffix(v string) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldNameTitle), v))
	})
}

// NameTitleEqualFold applies the EqualFold predicate on the "NameTitle" field.
func NameTitleEqualFold(v string) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldNameTitle), v))
	})
}

// NameTitleContainsFold applies the ContainsFold predicate on the "NameTitle" field.
func NameTitleContainsFold(v string) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldNameTitle), v))
	})
}

// HasDoctor applies the HasEdge predicate on the "doctor" edge.
func HasDoctor() predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DoctorTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DoctorTable, DoctorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDoctorWith applies the HasEdge predicate on the "doctor" edge with a given conditions (other predicates).
func HasDoctorWith(preds ...predicate.Doctor) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(DoctorInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DoctorTable, DoctorColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Nametitle) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Nametitle) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Nametitle) predicate.Nametitle {
	return predicate.Nametitle(func(s *sql.Selector) {
		p(s.Not())
	})
}
