// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pmn-kao/app/ent/degree"
	"github.com/pmn-kao/app/ent/doctor"
)

// DegreeCreate is the builder for creating a Degree entity.
type DegreeCreate struct {
	config
	mutation *DegreeMutation
	hooks    []Hook
}

// SetDegree sets the Degree field.
func (dc *DegreeCreate) SetDegree(s string) *DegreeCreate {
	dc.mutation.SetDegree(s)
	return dc
}

// AddDoctorIDs adds the doctor edge to Doctor by ids.
func (dc *DegreeCreate) AddDoctorIDs(ids ...int) *DegreeCreate {
	dc.mutation.AddDoctorIDs(ids...)
	return dc
}

// AddDoctor adds the doctor edges to Doctor.
func (dc *DegreeCreate) AddDoctor(d ...*Doctor) *DegreeCreate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return dc.AddDoctorIDs(ids...)
}

// Mutation returns the DegreeMutation object of the builder.
func (dc *DegreeCreate) Mutation() *DegreeMutation {
	return dc.mutation
}

// Save creates the Degree in the database.
func (dc *DegreeCreate) Save(ctx context.Context) (*Degree, error) {
	if _, ok := dc.mutation.Degree(); !ok {
		return nil, &ValidationError{Name: "Degree", err: errors.New("ent: missing required field \"Degree\"")}
	}
	if v, ok := dc.mutation.Degree(); ok {
		if err := degree.DegreeValidator(v); err != nil {
			return nil, &ValidationError{Name: "Degree", err: fmt.Errorf("ent: validator failed for field \"Degree\": %w", err)}
		}
	}
	var (
		err  error
		node *Degree
	)
	if len(dc.hooks) == 0 {
		node, err = dc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DegreeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dc.mutation = mutation
			node, err = dc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(dc.hooks) - 1; i >= 0; i-- {
			mut = dc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DegreeCreate) SaveX(ctx context.Context) *Degree {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dc *DegreeCreate) sqlSave(ctx context.Context) (*Degree, error) {
	d, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	d.ID = int(id)
	return d, nil
}

func (dc *DegreeCreate) createSpec() (*Degree, *sqlgraph.CreateSpec) {
	var (
		d     = &Degree{config: dc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: degree.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: degree.FieldID,
			},
		}
	)
	if value, ok := dc.mutation.Degree(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: degree.FieldDegree,
		})
		d.Degree = value
	}
	if nodes := dc.mutation.DoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   degree.DoctorTable,
			Columns: []string{degree.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return d, _spec
}
