// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pmn-kao/app/ent/degree"
	"github.com/pmn-kao/app/ent/department"
	"github.com/pmn-kao/app/ent/doctor"
	"github.com/pmn-kao/app/ent/nametitle"
)

// DoctorCreate is the builder for creating a Doctor entity.
type DoctorCreate struct {
	config
	mutation *DoctorMutation
	hooks    []Hook
}

// SetEmail sets the Email field.
func (dc *DoctorCreate) SetEmail(s string) *DoctorCreate {
	dc.mutation.SetEmail(s)
	return dc
}

// SetPassword sets the Password field.
func (dc *DoctorCreate) SetPassword(s string) *DoctorCreate {
	dc.mutation.SetPassword(s)
	return dc
}

// SetName sets the Name field.
func (dc *DoctorCreate) SetName(s string) *DoctorCreate {
	dc.mutation.SetName(s)
	return dc
}

// SetTel sets the Tel field.
func (dc *DoctorCreate) SetTel(s string) *DoctorCreate {
	dc.mutation.SetTel(s)
	return dc
}

// SetDepartmentID sets the department edge to Department by id.
func (dc *DoctorCreate) SetDepartmentID(id int) *DoctorCreate {
	dc.mutation.SetDepartmentID(id)
	return dc
}

// SetNillableDepartmentID sets the department edge to Department by id if the given value is not nil.
func (dc *DoctorCreate) SetNillableDepartmentID(id *int) *DoctorCreate {
	if id != nil {
		dc = dc.SetDepartmentID(*id)
	}
	return dc
}

// SetDepartment sets the department edge to Department.
func (dc *DoctorCreate) SetDepartment(d *Department) *DoctorCreate {
	return dc.SetDepartmentID(d.ID)
}

// SetDegreeID sets the degree edge to Degree by id.
func (dc *DoctorCreate) SetDegreeID(id int) *DoctorCreate {
	dc.mutation.SetDegreeID(id)
	return dc
}

// SetNillableDegreeID sets the degree edge to Degree by id if the given value is not nil.
func (dc *DoctorCreate) SetNillableDegreeID(id *int) *DoctorCreate {
	if id != nil {
		dc = dc.SetDegreeID(*id)
	}
	return dc
}

// SetDegree sets the degree edge to Degree.
func (dc *DoctorCreate) SetDegree(d *Degree) *DoctorCreate {
	return dc.SetDegreeID(d.ID)
}

// SetNametitleID sets the nametitle edge to Nametitle by id.
func (dc *DoctorCreate) SetNametitleID(id int) *DoctorCreate {
	dc.mutation.SetNametitleID(id)
	return dc
}

// SetNillableNametitleID sets the nametitle edge to Nametitle by id if the given value is not nil.
func (dc *DoctorCreate) SetNillableNametitleID(id *int) *DoctorCreate {
	if id != nil {
		dc = dc.SetNametitleID(*id)
	}
	return dc
}

// SetNametitle sets the nametitle edge to Nametitle.
func (dc *DoctorCreate) SetNametitle(n *Nametitle) *DoctorCreate {
	return dc.SetNametitleID(n.ID)
}

// Mutation returns the DoctorMutation object of the builder.
func (dc *DoctorCreate) Mutation() *DoctorMutation {
	return dc.mutation
}

// Save creates the Doctor in the database.
func (dc *DoctorCreate) Save(ctx context.Context) (*Doctor, error) {
	if _, ok := dc.mutation.Email(); !ok {
		return nil, &ValidationError{Name: "Email", err: errors.New("ent: missing required field \"Email\"")}
	}
	if v, ok := dc.mutation.Email(); ok {
		if err := doctor.EmailValidator(v); err != nil {
			return nil, &ValidationError{Name: "Email", err: fmt.Errorf("ent: validator failed for field \"Email\": %w", err)}
		}
	}
	if _, ok := dc.mutation.Password(); !ok {
		return nil, &ValidationError{Name: "Password", err: errors.New("ent: missing required field \"Password\"")}
	}
	if v, ok := dc.mutation.Password(); ok {
		if err := doctor.PasswordValidator(v); err != nil {
			return nil, &ValidationError{Name: "Password", err: fmt.Errorf("ent: validator failed for field \"Password\": %w", err)}
		}
	}
	if _, ok := dc.mutation.Name(); !ok {
		return nil, &ValidationError{Name: "Name", err: errors.New("ent: missing required field \"Name\"")}
	}
	if v, ok := dc.mutation.Name(); ok {
		if err := doctor.NameValidator(v); err != nil {
			return nil, &ValidationError{Name: "Name", err: fmt.Errorf("ent: validator failed for field \"Name\": %w", err)}
		}
	}
	if _, ok := dc.mutation.Tel(); !ok {
		return nil, &ValidationError{Name: "Tel", err: errors.New("ent: missing required field \"Tel\"")}
	}
	if v, ok := dc.mutation.Tel(); ok {
		if err := doctor.TelValidator(v); err != nil {
			return nil, &ValidationError{Name: "Tel", err: fmt.Errorf("ent: validator failed for field \"Tel\": %w", err)}
		}
	}
	var (
		err  error
		node *Doctor
	)
	if len(dc.hooks) == 0 {
		node, err = dc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*DoctorMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			dc.mutation = mutation
			node, err = dc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(dc.hooks) - 1; i >= 0; i-- {
			mut = dc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, dc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DoctorCreate) SaveX(ctx context.Context) *Doctor {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dc *DoctorCreate) sqlSave(ctx context.Context) (*Doctor, error) {
	d, _spec := dc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	d.ID = int(id)
	return d, nil
}

func (dc *DoctorCreate) createSpec() (*Doctor, *sqlgraph.CreateSpec) {
	var (
		d     = &Doctor{config: dc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: doctor.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: doctor.FieldID,
			},
		}
	)
	if value, ok := dc.mutation.Email(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: doctor.FieldEmail,
		})
		d.Email = value
	}
	if value, ok := dc.mutation.Password(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: doctor.FieldPassword,
		})
		d.Password = value
	}
	if value, ok := dc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: doctor.FieldName,
		})
		d.Name = value
	}
	if value, ok := dc.mutation.Tel(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: doctor.FieldTel,
		})
		d.Tel = value
	}
	if nodes := dc.mutation.DepartmentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   doctor.DepartmentTable,
			Columns: []string{doctor.DepartmentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: department.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dc.mutation.DegreeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   doctor.DegreeTable,
			Columns: []string{doctor.DegreeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: degree.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dc.mutation.NametitleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   doctor.NametitleTable,
			Columns: []string{doctor.NametitleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: nametitle.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return d, _spec
}
