// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pmn-kao/app/ent/doctor"
	"github.com/pmn-kao/app/ent/nametitle"
	"github.com/pmn-kao/app/ent/predicate"
)

// NametitleUpdate is the builder for updating Nametitle entities.
type NametitleUpdate struct {
	config
	hooks      []Hook
	mutation   *NametitleMutation
	predicates []predicate.Nametitle
}

// Where adds a new predicate for the builder.
func (nu *NametitleUpdate) Where(ps ...predicate.Nametitle) *NametitleUpdate {
	nu.predicates = append(nu.predicates, ps...)
	return nu
}

// SetNameTitle sets the NameTitle field.
func (nu *NametitleUpdate) SetNameTitle(s string) *NametitleUpdate {
	nu.mutation.SetNameTitle(s)
	return nu
}

// AddDoctorIDs adds the doctor edge to Doctor by ids.
func (nu *NametitleUpdate) AddDoctorIDs(ids ...int) *NametitleUpdate {
	nu.mutation.AddDoctorIDs(ids...)
	return nu
}

// AddDoctor adds the doctor edges to Doctor.
func (nu *NametitleUpdate) AddDoctor(d ...*Doctor) *NametitleUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return nu.AddDoctorIDs(ids...)
}

// Mutation returns the NametitleMutation object of the builder.
func (nu *NametitleUpdate) Mutation() *NametitleMutation {
	return nu.mutation
}

// RemoveDoctorIDs removes the doctor edge to Doctor by ids.
func (nu *NametitleUpdate) RemoveDoctorIDs(ids ...int) *NametitleUpdate {
	nu.mutation.RemoveDoctorIDs(ids...)
	return nu
}

// RemoveDoctor removes doctor edges to Doctor.
func (nu *NametitleUpdate) RemoveDoctor(d ...*Doctor) *NametitleUpdate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return nu.RemoveDoctorIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (nu *NametitleUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := nu.mutation.NameTitle(); ok {
		if err := nametitle.NameTitleValidator(v); err != nil {
			return 0, &ValidationError{Name: "NameTitle", err: fmt.Errorf("ent: validator failed for field \"NameTitle\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(nu.hooks) == 0 {
		affected, err = nu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NametitleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			nu.mutation = mutation
			affected, err = nu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(nu.hooks) - 1; i >= 0; i-- {
			mut = nu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NametitleUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NametitleUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NametitleUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (nu *NametitleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   nametitle.Table,
			Columns: nametitle.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: nametitle.FieldID,
			},
		},
	}
	if ps := nu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.NameTitle(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: nametitle.FieldNameTitle,
		})
	}
	if nodes := nu.mutation.RemovedDoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   nametitle.DoctorTable,
			Columns: []string{nametitle.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nu.mutation.DoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   nametitle.DoctorTable,
			Columns: []string{nametitle.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nametitle.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// NametitleUpdateOne is the builder for updating a single Nametitle entity.
type NametitleUpdateOne struct {
	config
	hooks    []Hook
	mutation *NametitleMutation
}

// SetNameTitle sets the NameTitle field.
func (nuo *NametitleUpdateOne) SetNameTitle(s string) *NametitleUpdateOne {
	nuo.mutation.SetNameTitle(s)
	return nuo
}

// AddDoctorIDs adds the doctor edge to Doctor by ids.
func (nuo *NametitleUpdateOne) AddDoctorIDs(ids ...int) *NametitleUpdateOne {
	nuo.mutation.AddDoctorIDs(ids...)
	return nuo
}

// AddDoctor adds the doctor edges to Doctor.
func (nuo *NametitleUpdateOne) AddDoctor(d ...*Doctor) *NametitleUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return nuo.AddDoctorIDs(ids...)
}

// Mutation returns the NametitleMutation object of the builder.
func (nuo *NametitleUpdateOne) Mutation() *NametitleMutation {
	return nuo.mutation
}

// RemoveDoctorIDs removes the doctor edge to Doctor by ids.
func (nuo *NametitleUpdateOne) RemoveDoctorIDs(ids ...int) *NametitleUpdateOne {
	nuo.mutation.RemoveDoctorIDs(ids...)
	return nuo
}

// RemoveDoctor removes doctor edges to Doctor.
func (nuo *NametitleUpdateOne) RemoveDoctor(d ...*Doctor) *NametitleUpdateOne {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return nuo.RemoveDoctorIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (nuo *NametitleUpdateOne) Save(ctx context.Context) (*Nametitle, error) {
	if v, ok := nuo.mutation.NameTitle(); ok {
		if err := nametitle.NameTitleValidator(v); err != nil {
			return nil, &ValidationError{Name: "NameTitle", err: fmt.Errorf("ent: validator failed for field \"NameTitle\": %w", err)}
		}
	}

	var (
		err  error
		node *Nametitle
	)
	if len(nuo.hooks) == 0 {
		node, err = nuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NametitleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			nuo.mutation = mutation
			node, err = nuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(nuo.hooks) - 1; i >= 0; i-- {
			mut = nuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NametitleUpdateOne) SaveX(ctx context.Context) *Nametitle {
	n, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

// Exec executes the query on the entity.
func (nuo *NametitleUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NametitleUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (nuo *NametitleUpdateOne) sqlSave(ctx context.Context) (n *Nametitle, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   nametitle.Table,
			Columns: nametitle.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: nametitle.FieldID,
			},
		},
	}
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Nametitle.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := nuo.mutation.NameTitle(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: nametitle.FieldNameTitle,
		})
	}
	if nodes := nuo.mutation.RemovedDoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   nametitle.DoctorTable,
			Columns: []string{nametitle.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := nuo.mutation.DoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   nametitle.DoctorTable,
			Columns: []string{nametitle.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	n = &Nametitle{config: nuo.config}
	_spec.Assign = n.assignValues
	_spec.ScanValues = n.scanValues()
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{nametitle.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return n, nil
}
