// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/pmn-kao/app/ent/doctor"
	"github.com/pmn-kao/app/ent/nametitle"
)

// NametitleCreate is the builder for creating a Nametitle entity.
type NametitleCreate struct {
	config
	mutation *NametitleMutation
	hooks    []Hook
}

// SetNameTitle sets the NameTitle field.
func (nc *NametitleCreate) SetNameTitle(s string) *NametitleCreate {
	nc.mutation.SetNameTitle(s)
	return nc
}

// AddDoctorIDs adds the doctor edge to Doctor by ids.
func (nc *NametitleCreate) AddDoctorIDs(ids ...int) *NametitleCreate {
	nc.mutation.AddDoctorIDs(ids...)
	return nc
}

// AddDoctor adds the doctor edges to Doctor.
func (nc *NametitleCreate) AddDoctor(d ...*Doctor) *NametitleCreate {
	ids := make([]int, len(d))
	for i := range d {
		ids[i] = d[i].ID
	}
	return nc.AddDoctorIDs(ids...)
}

// Mutation returns the NametitleMutation object of the builder.
func (nc *NametitleCreate) Mutation() *NametitleMutation {
	return nc.mutation
}

// Save creates the Nametitle in the database.
func (nc *NametitleCreate) Save(ctx context.Context) (*Nametitle, error) {
	if _, ok := nc.mutation.NameTitle(); !ok {
		return nil, &ValidationError{Name: "NameTitle", err: errors.New("ent: missing required field \"NameTitle\"")}
	}
	if v, ok := nc.mutation.NameTitle(); ok {
		if err := nametitle.NameTitleValidator(v); err != nil {
			return nil, &ValidationError{Name: "NameTitle", err: fmt.Errorf("ent: validator failed for field \"NameTitle\": %w", err)}
		}
	}
	var (
		err  error
		node *Nametitle
	)
	if len(nc.hooks) == 0 {
		node, err = nc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*NametitleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			nc.mutation = mutation
			node, err = nc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(nc.hooks) - 1; i >= 0; i-- {
			mut = nc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, nc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (nc *NametitleCreate) SaveX(ctx context.Context) *Nametitle {
	v, err := nc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (nc *NametitleCreate) sqlSave(ctx context.Context) (*Nametitle, error) {
	n, _spec := nc.createSpec()
	if err := sqlgraph.CreateNode(ctx, nc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	n.ID = int(id)
	return n, nil
}

func (nc *NametitleCreate) createSpec() (*Nametitle, *sqlgraph.CreateSpec) {
	var (
		n     = &Nametitle{config: nc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: nametitle.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: nametitle.FieldID,
			},
		}
	)
	if value, ok := nc.mutation.NameTitle(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: nametitle.FieldNameTitle,
		})
		n.NameTitle = value
	}
	if nodes := nc.mutation.DoctorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   nametitle.DoctorTable,
			Columns: []string{nametitle.DoctorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: doctor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return n, _spec
}
