// Code generated by entc, DO NOT EDIT.

package ent

import (
	"github.com/pmn-kao/app/ent/degree"
	"github.com/pmn-kao/app/ent/department"
	"github.com/pmn-kao/app/ent/doctor"
	"github.com/pmn-kao/app/ent/nametitle"
	"github.com/pmn-kao/app/ent/schema"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	degreeFields := schema.Degree{}.Fields()
	_ = degreeFields
	// degreeDescDegree is the schema descriptor for Degree field.
	degreeDescDegree := degreeFields[0].Descriptor()
	// degree.DegreeValidator is a validator for the "Degree" field. It is called by the builders before save.
	degree.DegreeValidator = degreeDescDegree.Validators[0].(func(string) error)
	departmentFields := schema.Department{}.Fields()
	_ = departmentFields
	// departmentDescDepartment is the schema descriptor for Department field.
	departmentDescDepartment := departmentFields[0].Descriptor()
	// department.DepartmentValidator is a validator for the "Department" field. It is called by the builders before save.
	department.DepartmentValidator = departmentDescDepartment.Validators[0].(func(string) error)
	doctorFields := schema.Doctor{}.Fields()
	_ = doctorFields
	// doctorDescEmail is the schema descriptor for Email field.
	doctorDescEmail := doctorFields[0].Descriptor()
	// doctor.EmailValidator is a validator for the "Email" field. It is called by the builders before save.
	doctor.EmailValidator = doctorDescEmail.Validators[0].(func(string) error)
	// doctorDescPassword is the schema descriptor for Password field.
	doctorDescPassword := doctorFields[1].Descriptor()
	// doctor.PasswordValidator is a validator for the "Password" field. It is called by the builders before save.
	doctor.PasswordValidator = doctorDescPassword.Validators[0].(func(string) error)
	// doctorDescName is the schema descriptor for Name field.
	doctorDescName := doctorFields[2].Descriptor()
	// doctor.NameValidator is a validator for the "Name" field. It is called by the builders before save.
	doctor.NameValidator = doctorDescName.Validators[0].(func(string) error)
	// doctorDescTel is the schema descriptor for Tel field.
	doctorDescTel := doctorFields[3].Descriptor()
	// doctor.TelValidator is a validator for the "Tel" field. It is called by the builders before save.
	doctor.TelValidator = doctorDescTel.Validators[0].(func(string) error)
	nametitleFields := schema.Nametitle{}.Fields()
	_ = nametitleFields
	// nametitleDescNameTitle is the schema descriptor for NameTitle field.
	nametitleDescNameTitle := nametitleFields[0].Descriptor()
	// nametitle.NameTitleValidator is a validator for the "NameTitle" field. It is called by the builders before save.
	nametitle.NameTitleValidator = nametitleDescNameTitle.Validators[0].(func(string) error)
}
