// Code generated by entc, DO NOT EDIT.

package degree

const (
	// Label holds the string label denoting the degree type in the database.
	Label = "degree"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDegree holds the string denoting the degree field in the database.
	FieldDegree = "degree"

	// EdgeDoctor holds the string denoting the doctor edge name in mutations.
	EdgeDoctor = "doctor"

	// Table holds the table name of the degree in the database.
	Table = "degrees"
	// DoctorTable is the table the holds the doctor relation/edge.
	DoctorTable = "doctors"
	// DoctorInverseTable is the table name for the Doctor entity.
	// It exists in this package in order to avoid circular dependency with the "doctor" package.
	DoctorInverseTable = "doctors"
	// DoctorColumn is the table column denoting the doctor relation/edge.
	DoctorColumn = "degree_id"
)

// Columns holds all SQL columns for degree fields.
var Columns = []string{
	FieldID,
	FieldDegree,
}

var (
	// DegreeValidator is a validator for the "Degree" field. It is called by the builders before save.
	DegreeValidator func(string) error
)
