/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Doctor
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersDoctor
 */
export interface ControllersDoctor {
    /**
     * 
     * @type {number}
     * @memberof ControllersDoctor
     */
    degree?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersDoctor
     */
    department?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersDoctor
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersDoctor
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersDoctor
     */
    nametitle?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersDoctor
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof ControllersDoctor
     */
    tel?: string;
}

export function ControllersDoctorFromJSON(json: any): ControllersDoctor {
    return ControllersDoctorFromJSONTyped(json, false);
}

export function ControllersDoctorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersDoctor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'degree': !exists(json, 'degree') ? undefined : json['degree'],
        'department': !exists(json, 'department') ? undefined : json['department'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'nametitle': !exists(json, 'nametitle') ? undefined : json['nametitle'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'tel': !exists(json, 'tel') ? undefined : json['tel'],
    };
}

export function ControllersDoctorToJSON(value?: ControllersDoctor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'degree': value.degree,
        'department': value.department,
        'email': value.email,
        'name': value.name,
        'nametitle': value.nametitle,
        'password': value.password,
        'tel': value.tel,
    };
}


