/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Doctor
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntDoctorEdges,
    EntDoctorEdgesFromJSON,
    EntDoctorEdgesFromJSONTyped,
    EntDoctorEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntDoctor
 */
export interface EntDoctor {
    /**
     * Email holds the value of the "Email" field.
     * @type {string}
     * @memberof EntDoctor
     */
    email?: string;
    /**
     * Name holds the value of the "Name" field.
     * @type {string}
     * @memberof EntDoctor
     */
    name?: string;
    /**
     * Password holds the value of the "Password" field.
     * @type {string}
     * @memberof EntDoctor
     */
    password?: string;
    /**
     * Tel holds the value of the "Tel" field.
     * @type {string}
     * @memberof EntDoctor
     */
    tel?: string;
    /**
     * 
     * @type {EntDoctorEdges}
     * @memberof EntDoctor
     */
    edges?: EntDoctorEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntDoctor
     */
    id?: number;
}

export function EntDoctorFromJSON(json: any): EntDoctor {
    return EntDoctorFromJSONTyped(json, false);
}

export function EntDoctorFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntDoctor {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'Email') ? undefined : json['Email'],
        'name': !exists(json, 'Name') ? undefined : json['Name'],
        'password': !exists(json, 'Password') ? undefined : json['Password'],
        'tel': !exists(json, 'Tel') ? undefined : json['Tel'],
        'edges': !exists(json, 'edges') ? undefined : EntDoctorEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntDoctorToJSON(value?: EntDoctor | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Email': value.email,
        'Name': value.name,
        'Password': value.password,
        'Tel': value.tel,
        'edges': EntDoctorEdgesToJSON(value.edges),
        'id': value.id,
    };
}


