/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Doctor
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntNametitleEdges,
    EntNametitleEdgesFromJSON,
    EntNametitleEdgesFromJSONTyped,
    EntNametitleEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntNametitle
 */
export interface EntNametitle {
    /**
     * NameTitle holds the value of the "NameTitle" field.
     * @type {string}
     * @memberof EntNametitle
     */
    nameTitle?: string;
    /**
     * 
     * @type {EntNametitleEdges}
     * @memberof EntNametitle
     */
    edges?: EntNametitleEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntNametitle
     */
    id?: number;
}

export function EntNametitleFromJSON(json: any): EntNametitle {
    return EntNametitleFromJSONTyped(json, false);
}

export function EntNametitleFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntNametitle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nameTitle': !exists(json, 'NameTitle') ? undefined : json['NameTitle'],
        'edges': !exists(json, 'edges') ? undefined : EntNametitleEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntNametitleToJSON(value?: EntNametitle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'NameTitle': value.nameTitle,
        'edges': EntNametitleEdgesToJSON(value.edges),
        'id': value.id,
    };
}


