export * from './ControllersDoctor';
export * from './EntDegree';
export * from './EntDegreeEdges';
export * from './EntDepartment';
export * from './EntDepartmentEdges';
export * from './EntDoctor';
export * from './EntDoctorEdges';
export * from './EntNametitle';
export * from './EntNametitleEdges';
